config/routes.rb
Rails.application.routes.draw do
  get 'profiles/show'

  devise_for :users
  resources :statuses
  get 'feed', to: 'statuses#index', as: :feed 
  root to: 'statuses#index'

  devise_scope :user do
    get 'register', to: 'devise/registrations#new', as: :register
    get 'login', to: 'devise/sessions#new', as: :login
    get 'logout', to: 'devise/sessions#destroy', as: :logout

  end

  get '/:id', to: 'profiles#show'

end

app/models/status.rb
class Status < ActiveRecord::Base
	belongs_to :user

	validates :content, presence: true,
						length: {minimum: 2}

	validates :user_id, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :profile_name, presence: true,
  							uniqueness: true,
  							format: {
  								with: /\A[a-zA-Z0-9_-]+\z/,
  								message: 'Must be formatted correctly'
  							}



  has_many :statuses
  
  def full_name
  	first_name + " " + last_name
  end
  def gravatar_url
    stripped_email = email.strip
    downcased_email = stripped_email.downcase
    hash = Digest::MD5.hexdigest(downcased_email)

    "http://gravatar.com/avatar/#{hash}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  
  add_flash_types :error
  add_flash_types :notice
  add_flash_types :alert
  include ActiveModel::ForbiddenAttributesProtection
  protect_from_forgery with: :exception
  before_filter :configure_devise_params_sign_up, if: :devise_controller?

  protected

  	def configure_devise_params_sign_up
  		devise_parameter_sanitizer.for(:sign_up) do |u|
  			u.permit(:first_name, :last_name, :profile_name, :email, :password, :password_confirmation, :current_password)

  	end
  end
  before_filter :configure_devise_params_account_update, if: :devise_controller?
  protected
  	def configure_devise_params_account_update
  		devise_parameter_sanitizer.for(:account_update) do |u|
  			u.permit(:first_name, :last_name, :profile_name, :email, :password, :password_confirmation, :current_password)

  	end
  end
  

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def show
    @user = User.find_by_profile_name(params[:id])
    if @user
      @statuses = @user.statuses.all
      render action: :show
    else
      render file: 'public/404', status: 404, formats: [:html]
    end
  end
end

app/controllers/statuses_controller.rb
class StatusesController < ApplicationController
  before_action :set_status, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!, only: [:new, :create, :edit, :update]

  # GET /statuses
  # GET /statuses.json
  def index
    @statuses = Status.all
  end

  # GET /statuses/1
  # GET /statuses/1.json
  def show
  end

  # GET /statuses/new
  def new
    @status = Status.new
  end

  # GET /statuses/1/edit
  def edit
  end

  # POST /statuses
  # POST /statuses.json
  def create
    @status = Status.new(status_params)

    respond_to do |format|
      if @status.save
        format.html { redirect_to @status, notice: 'Status was successfully created.' }
        format.json { render :show, status: :created, location: @status }
      else
        format.html { render :new }
        format.json { render json: @status.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /statuses/1
  # PATCH/PUT /statuses/1.json
  def update
    respond_to do |format|
      if @status.update(status_params)
        format.html { redirect_to @status, notice: 'Status was successfully updated.' }
        format.json { render :show, status: :ok, location: @status }
      else
        format.html { render :edit }
        format.json { render json: @status.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /statuses/1
  # DELETE /statuses/1.json
  def destroy
    @status.destroy
    respond_to do |format|
      format.html { redirect_to statuses_url, notice: 'Status was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_status
      @status = Status.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def status_params
      params.require(:status).permit(:content, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

	def flash_class(type)
		case type 
		when :alert
			"alert-error"
		when :notice
			"alert-info"
		else
			""
		end
	end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/statuses_helper.rb
module StatusesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Treebook</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
 
      <!-- .btn-navbar is used as the toggle for collapsed navbar content -->
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
 
      <!-- Be sure to leave the brand out there if you want it shown -->
      <a class="brand" href="#">Treebook</a>

      <!-- Everything you want hidden at 940px or less, place within here -->
      <div class="nav-collapse collapse navbar-responsive-collapse">
      	<ul class="nav">
      		<li><%= link_to "All Statuses", feed_path %></li>
      	<li class="dropdown">
      		<a href="#" class="dropdown-toggle" data-toggle="dropdown">
      			Dropdown 
      			<b class="caret"></b>
      		</a>
      		<ul class="dropdown-menu">
      			<li>
      				<a href="#">Test 1</a>
      			</li>
      			<li>
      				<a href="#">Test 2</a>
      			</li>
      			<li class="divider"></li>
      			<li class="nav-header">Nav header test</li>
      			<li>
      				<a href="#">Seperate Link</a>
      			</li>
      		</ul>
      		</li>
      	</ul>
        <ul class="nav pull-right">
          <% if user_signed_in? %>
            <li><%= link_to current_user.full_name, edit_user_registration_path %></li>
            <li><%= link_to "Log Out", logout_path%></li>
          <% else %>
            <li><%= link_to "Register", register_path %></li>
            <li><%= link_to "Log in", login_path %></li>
          <% end %>

        </ul>
        <!-- .nav, .navbar-search, .navbar-form, etc -->
        <form class="navbar-search pull-right" action>
        	<input type="text" class="search-query span2" placeholder="Search">
        </form>
        
      </div>
 
    </div>
  </div>
</div>
	<div class="container">
    <% if flash[:notice] %>
    <div class="alert alert-info">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <%= flash[:notice] %>
    </div>
    <% end %>
    <% if flash[:alert] %>
    <div class="alert alert-error">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <%= flash[:alert] %>
    </div>
    <% end %>
<%= yield %>
	</div>

</body>
</html>

app/views/profiles/show.html.erb
<div class="page-header">
  <h1><%= @user.full_name %></h1>
</div>

<% if @statuses %>
  <% @statuses.each do |status| %>
    <div class="well">
      <%= status.content %>
      <hr />
      <%= link_to time_ago_in_words(status.created_at), status_path(status) %> ago
    </div>
  <% end %>
<% end %>

app/views/statuses/_form.html.erb
<%= simple_form_for(@status, html: {class: "form-horizontal"}) do |f| %>
  <% if @status.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@status.errors.count, "error") %> prohibited this status from being saved:</h2>

      <ul>
      <% @status.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.input :user_id, collection: User.all, label_method: :full_name %>
  <%= f.input :content %>
  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/statuses/edit.html.erb
<h1>Editing status</h1>

<%= render 'form' %>

<%= link_to 'Show', @status %> |
<%= link_to 'Back', statuses_path %>

app/views/statuses/index.html.erb
<div class="page-header" style="color: white;">
  <h1>All of the Statuses</h1>
</div>
<div id="Post Button" style="padding-bottom: 15px;">
<%= link_to "Post a New Status", new_status_path, class: "btn btn-info" %>
</div>
<% @statuses.each do |status| %>
<div class="well">
<div class="status">
  <div class="row">
    
  <div class="span1">
    <%= image_tag status.user.gravatar_url %>
  </div>
  <div class="span7">
  <strong><%= status.user.full_name %></strong>
  <p><%= status.content %></p>
  <div class="meta">
    <%= link_to  time_ago_in_words(status.created_at) + " ago", status %>
    <span class="admin">
      | <%= link_to "Edit", edit_status_path(status)%> |
      <%= link_to "Delete", status, method: :delete, data: { confirm: "Are you sure you want to delete?"}%>

    </span>
  </div>
  </div>
</div>
</div>
</div>
<% end %>

app/views/statuses/new.html.erb
<div class="well">
<h1>New status</h1>

<%= render 'form' %>

<%= link_to 'Back', statuses_path %>
</div>

app/views/statuses/show.html.erb
<div class="well">
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @status.user.full_name %>
</p>

<p>
  <strong>Content:</strong>
  <%= @status.content %>
</p>

<%= link_to 'Edit', edit_status_path(@status) %> |
<%= link_to 'Back', statuses_path %>
</div>